{% set name = "tornado_m2crypto" %}
{% set version = "0.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/chaen/tornado_m2crypto.git
  git_rev: master

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    # Mark as requiring Python 3 to avoid the enum34 requirement
    - python >=3.4
    - m2crypto
    - tornado

test:
  imports:
    - tornado_m2crypto
    - tornado_m2crypto.m2httputil
    # TODO Broken in Python 3
    # - tornado_m2crypto.m2iostream
    - tornado_m2crypto.m2netutil
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/chaen/tornado_m2crypto
  summary: Extension to run tornado with M2Crypto instead of the standard python SSL module
  # TODO license: Apache-2.0
  # TODO license_file: LICENSE
