name: Greet Everyone
on: [push]

jobs:
  build:
    name: Build installer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        run: |
          wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
          bash Miniforge3-Linux-x86_64.sh -b -p $HOME/miniforge
          eval "$(${HOME}/miniforge/bin/conda shell.bash hook)"
          conda install --yes constructor
      - name: Create installer
        run: constructor . --platform=linux-64
      - name: Upload installer
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: |
            DIRACOS-*.sh

  basic_tests:
    name: Basic tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download installer
        uses: actions/download-artifact@v2
        with:
          name: homework
      - name: Test CentOS 7
        run: run_basic_tests.sh centos:7
